name: Bug Report
description: Found a bug in Builder? Create a report!
title: "Insert title here"
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and the expected behavior
      placeholder: A clear and concise description of what the bug is, and what you expect to happen instead.
    validations:
      required: true
  - type: textarea
    id: error-log
    attributes:
      label: Error log
      description: The full error message
      placeholder: The full error message
    validations:
      required: true
  - type: checkboxes
    id: error-platform
    attributes:
      label: Platform
      description: Platforms that experience errors
      options:
        - label: iOS
          required: false
        - label: macOS
          required: false
        - label: tvOS
          required: false
        - label: watchOS
          required: false
  - type: input
    id: macos-version
    attributes:
      label: macOS version
      description: Which macOS version are you using?
      placeholder: "13.0"
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Which package version are you using?
      placeholder: "1.1.0"
    validations:
      required: true
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
      description: Which version of Xcode are you using?
      placeholder: "15.0.0"
    validations:
      required: true
